// AUTOMATICALLY GENERATED BY BUILDINC v0.2.284 TOOL
// LAST BUILD (CMAKE): 2023-04-30 21:08:05

#pragma once

#ifndef BUILDINCVERSION_BUILDNUMBER_HEADER_H
#define BUILDINCVERSION_BUILDNUMBER_HEADER_H

#include <cstdint>

namespace BuildIncVersion
{
		 // You can modify major and minor
		constexpr uint32_t major = 0;
		constexpr uint32_t minor = 2;

		 // Do not modify these
		constexpr uint32_t build = 286;
		
		constexpr uint32_t version = major * 10000 + minor * 1000 + build;
		constexpr uint64_t random_seed = 0x43e9e1a648a722d3;
		
		constexpr char version_string[] = "v0.2.286";
		constexpr char build_time_string[] = "2023-04-30 21:08:05";
		constexpr char phrase[] = "maybe-clubbed-duration";
		constexpr char calver[] = "2023.17.286";
		constexpr char uuid[] = "CFDD984D-845F-4A24-A31F-51D11A33598E";

		// Copy paste to import to your project
		/*
			constexpr auto major = BuildIncVersion::major;
			constexpr auto minor = BuildIncVersion::minor;
			constexpr auto build = BuildIncVersion::build;
			constexpr auto version = BuildIncVersion::version;
			constexpr auto random_seed = BuildIncVersion::random_seed;
			
			constexpr auto version_string = BuildIncVersion::version_string;
			constexpr auto build_time_string = BuildIncVersion::build_time_string;
			constexpr auto phrase = BuildIncVersion::phrase;
			constexpr auto calver = BuildIncVersion::calver;
			constexpr auto uuid = BuildIncVersion::uuid;
		*/
}
#endif // BUILDINCVERSION_BUILDNUMBER_HEADER_H

