// AUTOMATICALLY GENERATED BY BUILDINC v0.2.259 TOOL
// LAST BUILD (CMAKE): 2023-03-26 19:45:41

#pragma once

#ifndef BUILDINCVERSION_BUILDNUMBER_HEADER_H
#define BUILDINCVERSION_BUILDNUMBER_HEADER_H

#include <cstdint>

namespace BuildIncVersion
{
		 // You can modify major and minor
		constexpr uint32_t major = 0;
		constexpr uint32_t minor = 2;

		 // Do not modify these
		constexpr uint32_t build = 262;
		
		constexpr uint32_t version = major * 10000 + minor * 1000 + build;
		constexpr uint64_t random_seed = 0x19b1ed5c680abe89;
		
		constexpr char version_string[] = "v0.2.262";
		constexpr char build_time_string[] = "2023-03-26 19:45:41";
		constexpr char phrase[] = "vividly-salaried-result";
		constexpr char calver[] = "2023.12.262";
		constexpr char uuid[] = "09CC218C-7EEB-4D61-82D6-FAE447439A4C";

		// Copy paste to import to your project
		/*
			constexpr auto major = BuildIncVersion::major;
			constexpr auto minor = BuildIncVersion::minor;
			constexpr auto build = BuildIncVersion::build;
			constexpr auto version = BuildIncVersion::version;
			constexpr auto random_seed = BuildIncVersion::random_seed;
			
			constexpr auto version_string = BuildIncVersion::version_string;
			constexpr auto build_time_string = BuildIncVersion::build_time_string;
			constexpr auto phrase = BuildIncVersion::phrase;
			constexpr auto calver = BuildIncVersion::calver;
			constexpr auto uuid = BuildIncVersion::uuid;
		*/
}
#endif // BUILDINCVERSION_BUILDNUMBER_HEADER_H

