// AUTOMATICALLY GENERATED BY BUILDINC v0.2.341 TOOL
// LAST BUILD (CMAKE): 2023-11-15 11:56:22

#pragma once

#ifndef MODULE_BUILDNUMBER_HEADER_H
#define MODULE_BUILDNUMBER_HEADER_H

#include <cstdint>

namespace module
{
	 // You can modify major and minor
	constexpr uint32_t major = 0;
	constexpr uint32_t minor = 0;

	 // Do not modify these
	constexpr uint32_t build = 2;
	
	constexpr uint32_t version = major * 100 + minor * 10 + build;
	constexpr uint64_t random_seed = 0xabd17960445d9875;
	
	constexpr char version_string[] = "v0.0.2";
	constexpr char build_time_string[] = "2023-11-15 11:56:22";
	constexpr char phrase[] = "naming-upscale-paternity";
	constexpr char calver[] = "2023.46.2";
	constexpr char uuid[] = "57C3A97D-5BD7-4CB0-8CC4-8FC75DA90805";

	// Copy paste to import to your project
	/*
		constexpr auto major = module::major;
		constexpr auto minor = module::minor;
		constexpr auto build = module::build;
		constexpr auto version = module::version;
		constexpr auto random_seed = module::random_seed;
			
		constexpr auto version_string = module::version_string;
		constexpr auto build_time_string = module::build_time_string;
		constexpr auto phrase = module::phrase;
		constexpr auto calver = module::calver;
		constexpr auto uuid = module::uuid;
	*/
}
#endif // MODULE_BUILDNUMBER_HEADER_H

