// AUTOMATICALLY GENERATED BY BUILDINC v0.2.286 TOOL
// LAST BUILD (CMAKE): 2023-04-30 21:12:36

#pragma once

#ifndef MODULEVERSION_BUILDNUMBER_HEADER_H
#define MODULEVERSION_BUILDNUMBER_HEADER_H

#include <cstdint>

namespace moduleVersion
{
	// You can modify major and minor
	constexpr uint32_t major = 0;
	constexpr uint32_t minor = 0;

	// Do not modify these
	constexpr uint32_t build = 1;

	constexpr uint32_t version     = major * 100 + minor * 10 + build;
	constexpr uint64_t random_seed = 0x8f0e'534a'9a90'1ad1;

	constexpr char version_string[]    = "v0.0.1";
	constexpr char build_time_string[] = "2023-04-30 21:12:36";
	constexpr char phrase[]            = "abacus-abacus-abacus";
	constexpr char calver[]            = "2023.17.1";
	constexpr char uuid[]              = "1AD11910-DF96-4CAE-8680-9FA02768424C";

	// Copy paste to import to your project
	/*
		constexpr auto major = moduleVersion::major;
		constexpr auto minor = moduleVersion::minor;
		constexpr auto build = moduleVersion::build;
		constexpr auto version = moduleVersion::version;
		constexpr auto random_seed = moduleVersion::random_seed;

		constexpr auto version_string = moduleVersion::version_string;
		constexpr auto build_time_string = moduleVersion::build_time_string;
		constexpr auto phrase = moduleVersion::phrase;
		constexpr auto calver = moduleVersion::calver;
		constexpr auto uuid = moduleVersion::uuid;
	*/
}
#endif // MODULEVERSION_BUILDNUMBER_HEADER_H
