name: Change post-build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Find and Replace
        uses: frabert/replace-string-action@v2.0
        with:
          include: "buildinc.vcxproj"
          string: '<PostBuildEventUseInBuild>true</PostBuildEventUseInBuild>'
          replace-with: '<PostBuildEventUseInBuild>true</PostBuildEventUseInBuild>'
          
